account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
app_name = 'account'

urlpatterns = [
  
 
  path('', views.dashboard , name='dashboard'),
  path('alert/create/', views.create_alert,name='create_alert'),
  path('alert/list/',views.alert_list,name='alert_list'),
  path('register/form/',views.register,name='RegisterForm'),
  path('login/',views.LoginView.as_view(),name='login'),
  path('logout',views.LogoutView.as_view(),name='logout'),
  path('academic/calender/',views.academic_calender,name='academic_calender'),
  path('timetable/',views.time_table,name='time_table'),
  path('syllabus/upload/', views.syllabus, name='syllabus'),

  # path('login/',auth_views.LoginView.as_view() , name='login'),
  # path('logout/',auth_views.LogoutView.as_view() , name='logged_out'),
  # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
  # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
  # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
  # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
  # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
  # path('register/',views.register, name='register'),
  # path('account/profile_edit/',views.basic_info ,name = 'edit_profile'),
  # path('account/media_upload/',views.edit_media , name = 'edit_media'),

  # path('account/signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
  # path('account/signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
  # path('account/signup/principal/', views.PrincipalSignUpView.as_view(), name='principal_signup'),
  #

  #All Student url
  path('feeds/', views.feeds, name='feeds'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vidyarthi/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home,name='home' ),
    path('account/', include('account.urls', namespace='account')),
    path('student/',include('student.urls', namespace='student')),
    path('schoolclasses', include('schoolclasses.urls',namespace='school')),
    path('employes/', include('employes.urls',namespace='employes')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/student/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>F</b>A{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Fella</b>Admin{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" style="margin-right: 90%" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

templates/student/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                    <li>
                    <a href="{% url 'student:dashboard' %}">
                        <i class="fa fa-dashboard"></i> <span>Dashbord</span>
                    </a>
                </li>
                 <li>
                    <a href="{% url 'student:feeds' %}">
                        <i class="fa fa-feed"></i> <span>Feeds</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-graduation-cap"></i> <span>Profile</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Students</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="#">
                                <i class="fa fa-user"></i> Another link
                            </a>
                        </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>